# Generated by Django 5.0.1 on 2024-09-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='AddToCart')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.CharField(max_length=100)),
            ],
        ),
    ]
