# Generated by Django 5.0.1 on 2024-09-02 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_addtocart'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
