# Generated by Django 5.0.1 on 2024-09-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_addtocart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
