# Generated by Django 5.0.1 on 2024-09-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_users_cart_addtocart_email_addtocart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='email',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='username',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='users_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.users_cart'),
        ),
        migrations.AlterField(
            model_name='users_cart',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
