# Generated by Django 5.0.1 on 2024-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_addtocart_email_remove_addtocart_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='restaurant_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
