# Generated by Django 5.0.1 on 2024-09-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_addtocart_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='restaurant_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
