# Generated by Django 5.0.1 on 2024-09-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_addtocart_restaurant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocart',
            name='restaurant_name',
        ),
    ]
