# Generated by Django 5.0.1 on 2024-09-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_addtocart_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='restaurant_name',
            field=models.CharField(default='restaurant_name', max_length=100),
        ),
    ]
