# Generated by Django 5.0.1 on 2024-09-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_order_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='cart_item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
