# Generated by Django 5.0.1 on 2024-09-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_remove_orderitems_order_remove_orderitems_cart_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='PlaceOrder')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.CharField(max_length=100)),
                ('restaurant_name', models.CharField(default='restaurant_name', max_length=100)),
                ('order_status', models.CharField(default='pending', max_length=100)),
                ('customer_name', models.CharField(default=None, max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('customer_location', models.CharField(max_length=100)),
                ('users_cart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.users_cart')),
            ],
        ),
    ]
