# Generated by Django 5.0.1 on 2024-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_placeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='current_time',
            field=models.CharField(default='datetime', max_length=100),
        ),
    ]
