# Generated by Django 5.0.1 on 2024-09-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_placeorder_current_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='current_time',
            new_name='current_datetime',
        ),
    ]
