# Generated by Django 5.0.1 on 2024-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_current_time_placeorder_current_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_cart',
            name='location',
            field=models.CharField(default='Location', max_length=200),
        ),
        migrations.AddField(
            model_name='users_cart',
            name='phone_number',
            field=models.CharField(default='0300*******', max_length=20),
        ),
    ]
