# Generated by Django 5.0.1 on 2024-09-13 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_placeorder_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='customer_location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='users_cart',
            name='location',
            field=models.CharField(default='Location', max_length=300),
        ),
        migrations.CreateModel(
            name='ConsumerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=155)),
                ('customer_id', models.CharField(max_length=155)),
                ('customer_location', models.CharField(max_length=255)),
                ('rider', models.CharField(max_length=155)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.users_cart')),
            ],
        ),
    ]
