# Generated by Django 5.0.1 on 2024-09-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_placeorder_customer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumerdata',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
