# Generated by Django 5.0.1 on 2024-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_rename_timestamp_consumerdata_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerdata',
            name='customer_id',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
