# Generated by Django 5.0.1 on 2024-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_alter_consumerdata_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerdata',
            name='customer_id',
            field=models.CharField(max_length=155),
        ),
    ]
