# Generated by Django 5.0.1 on 2024-09-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_consumerdata_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerdata',
            name='customer_phone',
            field=models.CharField(default='0300*******', max_length=12),
        ),
        migrations.AddField(
            model_name='consumerdata',
            name='rider_phone',
            field=models.CharField(default='0300*******', max_length=12),
        ),
    ]
