# Generated by Django 5.0.1 on 2024-09-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_remove_consumerdata_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrderGST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_amount', models.CharField(default='0.00', max_length=100)),
                ('placeorder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.placeorder')),
            ],
        ),
    ]
