# Generated by Django 5.0.1 on 2024-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_placeordergst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaceOrderGST',
        ),
    ]
