# Generated by Django 5.1.1 on 2024-10-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_users_cart_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_location', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.CharField(max_length=255)),
                ('total_price', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=155)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.users_cart')),
            ],
        ),
    ]
