# Generated by Django 5.1.1 on 2024-10-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_orderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
