# Generated by Django 5.0.1 on 2024-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='google@example.com', max_length=50, unique=True)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('bio', models.TextField(default="Rider's Bio")),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_image', models.ImageField(upload_to='RiderProfileImage')),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
