# Generated by Django 5.0.1 on 2024-09-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_orderdetails_delete_pendingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='rider_name',
            field=models.CharField(default='rider_name', max_length=100),
        ),
    ]
