# Generated by Django 5.1.1 on 2024-10-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_orderdetails_rider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_completed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='wallet',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
