# Generated by Django 5.1.1 on 2024-10-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_remove_orderdetails_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='rider_name',
        ),
    ]
