# Generated by Django 5.1.1 on 2024-10-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0006_remove_orderdetails_rider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_completed',
            field=models.IntegerField(default=0),
        ),
    ]
