# Generated by Django 5.1.1 on 2024-10-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0009_alter_orderdetails_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
