# Generated by Django 5.0.1 on 2024-08-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=30)),
                ('restaurant_slogan', models.CharField(max_length=100)),
                ('restaurant_description', models.TextField(default='Restaurant Description')),
                ('restaurant_image', models.ImageField(upload_to='restaurant_profile_image')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='google@example.com', max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_description', models.TextField(default='Food Item Description')),
                ('item_image', models.ImageField(upload_to='Add-Food-Items-Images')),
                ('item_price', models.CharField(blank=True, max_length=6, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.register_partner')),
            ],
        ),
    ]
