# Generated by Django 5.0.1 on 2024-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_register_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_partner',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
