# Generated by Django 5.1.1 on 2024-10-12 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_register_partner_restaurant_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.CharField(blank=True, max_length=6, null=True)),
                ('order_date', models.CharField(max_length=50)),
                ('rider', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('order_completed', models.CharField(max_length=50)),
                ('wallet', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.register_partner')),
            ],
        ),
    ]
