# Generated by Django 5.1.1 on 2024-10-12 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_date',
        ),
    ]
